name: loopgym
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  - pip:
      - torch==2.6.0
      - vllm==0.8.0
      - transformers==4.57.1
      - accelerate
      - openai
      - numpy
      - pandas
      - pyarrow
      - z3-solver
      - fastapi
      - uvicorn
      - pydantic
